"""initial schema

Revision ID: 8561f165200a
Revises: 
Create Date: 2026-06-04 06:10:08.250443
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8561f165200a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_seat',
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('current_seats', sa.Integer(), nullable=False),
    sa.Column('waitlist_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_seats <= max_seats', name=op.f('ck_category_seat_current_seats_within_max')),
    sa.CheckConstraint('current_seats >= 0', name=op.f('ck_category_seat_current_seats_non_negative')),
    sa.CheckConstraint('waitlist_count >= 0', name=op.f('ck_category_seat_waitlist_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_seat')),
    sa.UniqueConstraint('category', name=op.f('uq_category_seat_category'))
    )
    op.create_table('distributor',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('primary_category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'waitlisted', 'active', 'suspended', name='distributor_status'), nullable=False),
    sa.Column('tier', sa.Enum('tier1', 'tier2', 'tier3', name='distributor_tier'), nullable=False),
    sa.Column('cumulative_gmv', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wallet_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('low_balance_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_accounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('return_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('packing_slip_template_id', sa.String(length=128), nullable=True),
    sa.Column('sample_unlocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributor')),
    sa.UniqueConstraint('email', name=op.f('uq_distributor_email'))
    )
    op.create_table('product',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_table('show',
    sa.Column('distributor_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'whatnot', name='platform'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'ended', 'cancelled', name='show_status'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor.id'], name=op.f('fk_show_distributor_id_distributor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_show'))
    )
    op.create_index('ix_show_distributor_scheduled', 'show', ['distributor_id', 'scheduled_at'], unique=False)
    op.create_table('sku',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('hts_code', sa.String(length=20), nullable=False),
    sa.Column('duty_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('landed_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cpsia_status', sa.Enum('not_required', 'pending', 'certified', 'failed', name='cpsia_status'), nullable=False),
    sa.Column('ca_metals_compliant', sa.Boolean(), nullable=False),
    sa.Column('prop65_flag', sa.Boolean(), nullable=False),
    sa.Column('ftc_jewelry_labeled', sa.Boolean(), nullable=False),
    sa.Column('price_floor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('daily_drop_qty', sa.Integer(), nullable=False),
    sa.Column('total_on_hand', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('catalog_status', sa.Enum('draft', 'compliance_pending', 'listed', 'blocked', name='catalog_status'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_drop_qty >= 0', name=op.f('ck_sku_daily_drop_qty_non_negative')),
    sa.CheckConstraint('duty_rate >= 0', name=op.f('ck_sku_duty_rate_non_negative')),
    sa.CheckConstraint('price_floor >= 0', name=op.f('ck_sku_price_floor_non_negative')),
    sa.CheckConstraint('total_on_hand >= 0', name=op.f('ck_sku_total_on_hand_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_sku_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku')),
    sa.UniqueConstraint('sku_code', name=op.f('uq_sku_sku_code'))
    )
    op.create_table('wallet_transaction',
    sa.Column('distributor_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('topup', 'sample_debit', 'wholesale_debit', 'refund', 'rebate', name='wallet_txn_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor.id'], name=op.f('fk_wallet_transaction_distributor_id_distributor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_transaction')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_wallet_transaction_idempotency_key'))
    )
    op.create_index('ix_wallet_transaction_distributor_id', 'wallet_transaction', ['distributor_id'], unique=False)
    op.create_table('compliance_record',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('check_type', sa.String(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_compliance_record_sku_id_sku')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_record'))
    )
    op.create_index('ix_compliance_record_sku_id', 'compliance_record', ['sku_id'], unique=False)
    op.create_table('daily_sku_drop',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('drop_date', sa.Date(), nullable=False),
    sa.Column('platform_scope', sa.Enum('global', 'per_platform', name='platform_scope'), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'whatnot', name='platform'), nullable=True),
    sa.Column('drop_qty', sa.Integer(), nullable=False),
    sa.Column('sold_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'assigned', 'live', 'sold_out', 'closed', name='drop_status'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(platform_scope = 'global' AND platform IS NULL) OR (platform_scope = 'per_platform' AND platform IS NOT NULL)", name=op.f('ck_daily_sku_drop_scope_platform_consistency')),
    sa.CheckConstraint('drop_qty >= 0', name=op.f('ck_daily_sku_drop_drop_qty_non_negative')),
    sa.CheckConstraint('sold_qty <= drop_qty', name=op.f('ck_daily_sku_drop_sold_within_drop')),
    sa.CheckConstraint('sold_qty >= 0', name=op.f('ck_daily_sku_drop_sold_qty_non_negative')),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_daily_sku_drop_sku_id_sku')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_sku_drop'))
    )
    op.create_index('uq_drop_global', 'daily_sku_drop', ['sku_id', 'drop_date', 'platform_scope'], unique=True, postgresql_where=sa.text('platform IS NULL'))
    op.create_index('uq_drop_per_platform', 'daily_sku_drop', ['sku_id', 'drop_date', 'platform_scope', 'platform'], unique=True, postgresql_where=sa.text('platform IS NOT NULL'))
    op.create_table('wholesale_price',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.Enum('tier1', 'tier2', 'tier3', name='distributor_tier'), nullable=False),
    sa.Column('wholesale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.CheckConstraint('wholesale_price >= 0', name=op.f('ck_wholesale_price_wholesale_price_non_negative')),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_wholesale_price_sku_id_sku')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wholesale_price')),
    sa.UniqueConstraint('sku_id', 'tier', name='uq_wholesale_price_sku_tier')
    )
    op.create_table('drop_assignment',
    sa.Column('daily_sku_drop_id', sa.BigInteger(), nullable=False),
    sa.Column('distributor_id', sa.BigInteger(), nullable=False),
    sa.Column('show_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['daily_sku_drop_id'], ['daily_sku_drop.id'], name=op.f('fk_drop_assignment_daily_sku_drop_id_daily_sku_drop')),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor.id'], name=op.f('fk_drop_assignment_distributor_id_distributor')),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], name=op.f('fk_drop_assignment_show_id_show')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drop_assignment')),
    sa.UniqueConstraint('daily_sku_drop_id', name='uq_drop_assignment_daily_sku_drop_id')
    )
    op.create_index('ix_drop_assignment_distributor_id', 'drop_assignment', ['distributor_id'], unique=False)
    op.create_index('ix_drop_assignment_show_id', 'drop_assignment', ['show_id'], unique=False)
    op.create_table('sales_order',
    sa.Column('distributor_id', sa.BigInteger(), nullable=False),
    sa.Column('daily_sku_drop_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('tiktok_api', 'whatnot_csv', name='sales_order_source'), nullable=False),
    sa.Column('external_order_id', sa.String(length=128), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('sale_unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wholesale_unit_price_snapshot', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('below_floor_flag', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ingested', 'priced', 'wallet_charged', 'routed', 'fulfilled', 'rejected', 'cancelled', name='sales_order_status'), nullable=False),
    sa.Column('wallet_txn_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_sku_drop_id'], ['daily_sku_drop.id'], name=op.f('fk_sales_order_daily_sku_drop_id_daily_sku_drop')),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor.id'], name=op.f('fk_sales_order_distributor_id_distributor')),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_sales_order_sku_id_sku')),
    sa.ForeignKeyConstraint(['wallet_txn_id'], ['wallet_transaction.id'], name=op.f('fk_sales_order_wallet_txn_id_wallet_transaction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_order')),
    sa.UniqueConstraint('source', 'external_order_id', name='uq_sales_order_source_external')
    )
    op.create_table('fulfillment',
    sa.Column('sales_order_id', sa.BigInteger(), nullable=False),
    sa.Column('oms_shipment_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('created', 'picked', 'shipped', 'delivered', 'exception', name='fulfillment_status'), nullable=False),
    sa.Column('tracking_no', sa.String(length=128), nullable=True),
    sa.Column('carrier', sa.String(length=64), nullable=True),
    sa.Column('return_address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('packing_slip_url', sa.String(length=512), nullable=True),
    sa.Column('last_webhook_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], name=op.f('fk_fulfillment_sales_order_id_sales_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fulfillment')),
    sa.UniqueConstraint('sales_order_id', name=op.f('uq_fulfillment_sales_order_id'))
    )
    op.create_table('product_return',
    sa.Column('sales_order_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('defective', 'buyer_remorse', name='return_type'), nullable=False),
    sa.Column('cost_owner', sa.Enum('newco', 'distributor', 'shared', name='return_cost_owner'), nullable=False),
    sa.Column('restock_qty', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wallet_txn_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], name=op.f('fk_product_return_sales_order_id_sales_order')),
    sa.ForeignKeyConstraint(['wallet_txn_id'], ['wallet_transaction.id'], name=op.f('fk_product_return_wallet_txn_id_wallet_transaction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_return'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_return')
    op.drop_table('fulfillment')
    op.drop_table('sales_order')
    op.drop_index('ix_drop_assignment_show_id', table_name='drop_assignment')
    op.drop_index('ix_drop_assignment_distributor_id', table_name='drop_assignment')
    op.drop_table('drop_assignment')
    op.drop_table('wholesale_price')
    op.drop_index('uq_drop_per_platform', table_name='daily_sku_drop', postgresql_where=sa.text('platform IS NOT NULL'))
    op.drop_index('uq_drop_global', table_name='daily_sku_drop', postgresql_where=sa.text('platform IS NULL'))
    op.drop_table('daily_sku_drop')
    op.drop_index('ix_compliance_record_sku_id', table_name='compliance_record')
    op.drop_table('compliance_record')
    op.drop_index('ix_wallet_transaction_distributor_id', table_name='wallet_transaction')
    op.drop_table('wallet_transaction')
    op.drop_table('sku')
    op.drop_index('ix_show_distributor_scheduled', table_name='show')
    op.drop_table('show')
    op.drop_table('product')
    op.drop_table('distributor')
    op.drop_table('category_seat')
    # ### end Alembic commands ###
    # Drop PG ENUM types (Alembic autogen does not emit these).
    for enum_name in (
        "distributor_status",
        "distributor_tier",
        "wallet_txn_type",
        "cpsia_status",
        "catalog_status",
        "platform",
        "platform_scope",
        "show_status",
        "drop_status",
        "sales_order_source",
        "sales_order_status",
        "fulfillment_status",
        "return_type",
        "return_cost_owner",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
