"""recap/ — Phase 5 (STUB, except the speaker section which is implemented).

PRD §7.7 直播复盘 (散场自动): duration, totals, Top10, L3 count, L1/L2 hit rate,
unknowns, leads, wechat adds, bookings/deals, topics, FAQ-to-review, ban-list.
Generated by the Sonnet tier (offline), pushed via Omega Telegram.

The 「主播红线表达监控」 section (§7.8.11) is ALREADY implemented in
olc/speaker_monitor/recap_hooks and can be composed into the full recap now.
The rest is blocked on ingestion + FAQ material.
"""
from ..speaker_monitor.recap_hooks import build_speaker_redline_section, render_markdown

__all__ = ["build_speaker_redline_section", "render_markdown"]
